---
- name: Copy all files 
  hosts: all
  become: yes
  remote_user: root
  vars:
    src_file: "/tmp/deployment/deployment_{{ lookup('pipe', 'date +%Y-%m-%d') }}/"
    destination_dir: "/opt/webadm/deployment/loyalty/staging/1.83.0/app/"
  tasks:
  
    - name: Copy all files from /test to the destination directory
      copy:
        src: "{{ src_file }}"
        dest: "{{ destination_dir }}"
        remote_src: yes
