---
- name: Recursively copy all files and backup if existing
  hosts: all
  vars:
    src_dir: "/tmp/deployment/deployment_2025-06-24"
    dest_dir: "/opt/webadm/deployment/loyalty/staging/1.83.0/app"
    backup_dir: "/tmp/deployment/backup_2025-06-24"
  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Find all files and directories to be copied
      find:
        paths: "{{ src_dir }}"
      register: files_and_dirs

    - name: Backup existing files and directories at destination
      shell: |
        dest_path="{{ dest_dir }}/{{ item.path | regex_replace('^' + src_dir + '/', '') }}"
        backup_path="{{ backup_dir }}/{{ item.path | regex_replace('^' + src_dir + '/', '') }}"
        if [ -e "$dest_path" ]; then
          mkdir -p "$(dirname "$backup_path")"
          mv "$dest_path" "$backup_path"
        fi
      args:
        executable: /bin/bash
      loop: "{{ files_and_dirs.files }}"
      loop_control:
        label: "{{ item.path | regex_replace('^' + src_dir + '/', '') }}"

    - name: Copy all files and directories recursively to destination
      synchronize:
        src: "{{ src_dir }}/"
        dest: "{{ dest_dir }}/"
        recursive: yes
        rsync_opts:
          - "--chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r"
