- name: Copy files and backup if existing
  hosts: all
  vars:
    src_dir: "/tmp/deployment/deployment_2025-06-24"
    dest_dir: "/opt/webadm/deployment/loyalty/staging/1.83.0/app"
    backup_dir: "/tmp/deployment/backup_2025-06-24"
  tasks:
    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Find files to be copied
      find:
        paths: "{{ src_dir }}"
        file_type: file
      register: files_to_copy

    - name: Backup existing destination files
      shell: |
        if [ -f "{{ dest_dir }}/{{ item.path | basename }}" ]; then
          mv "{{ dest_dir }}/{{ item.path | basename }}" "{{ backup_dir }}/"
        fi
      args:
        executable: /bin/bash
      loop: "{{ files_to_copy.files }}"
      loop_control:
        label: "{{ item.path | basename }}"

    - name: Copy files to destination
      copy:
        src: "{{ item.path }}"
        dest: "{{ dest_dir }}/"
        mode: '0644'
      loop: "{{ files_to_copy.files }}"
      loop_control:
        label: "{{ item.path | basename }}"
