---
- name: Transfer /tmp/deployment from 192.168.100.32 to 192.168.100.33 using rsync with SSH password
  hosts: 192.168.100.33
  gather_facts: no
  vars:
    rsync_user: root
    rsync_password: "22785Jaz"
  tasks:
    - name: Ensure sshpass is installed
      ansible.builtin.package:
        name: sshpass
        state: present
      become: yes

    - name: Rsync files from 192.168.100.32:/tmp/deployment to /tmp/deployment on 192.168.100.33
      ansible.builtin.command: >
        sshpass -p '{{ rsync_password }}' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" {{ rsync_user }}@192.168.100.32:/tmp/deployment/ /tmp/deployment/
      become: yes
