---
- name: Copy all files from remote host to local directory with rsync options
  hosts: all
  become: yes

 vars_prompt:
    - name: ssh_password
      prompt: "22785Jaz"
      private: yes

  vars:
    src_server: "root@192.168.100.32"
    src_file: "/tmp/deployment/deployment_{{ lookup('pipe', 'date +%Y-%m-%d') }}/"
    destination_dir: "/tmp/deployment/deployment_{{ lookup('pipe', 'date +%Y-%m-%d') }}/"
    
  tasks:
    - name: Synchronize files from remote host
      ansible.builtin.synchronize:
        src: "{{ src_server }}:{{ src_file }}"
        dest: "{{ destination_dir }}"
        mode: pull
        archive: yes        # -a
        checksum: yes       # -c
        compress: yes       # -z
        perms: yes          # -p (implied by -a, but explicit here)
        verbose: yes        # -v
        partial: yes        # -P
        rsync_opts:
          - "--stats"
        rsync_path: "sshpass -p '{{ ssh_password }}' rsync"
