---
- name: Copy application.properties from remote host to control node
  hosts: 192.168.100.33
  tasks:
    - name: Fetch application.properties from remote host
      fetch:
        src: /opt/webadm/deployment/loyalty/staging/1.83.0/app/linux.yml
        dest: "/tmp/deployment/deployment_{{ lookup('pipe', 'date +%Y-%m-%d') }}"
        flat: yes
