---
- name: Copy file from remote source to host using rsync
  hosts: all
  become: yes
  vars:
    src_host: 192.168.100.33
    src_path: "/tmp/source"
    dest_path: /tmp/deployment/deployment_{{ lookup('pipe', 'date +%Y-%m-%d') }}
  tasks:
    - name: Copy file or directory from remote source to host with rsync
      ansible.builtin.synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        mode: pull
        recursive: yes   # Set to 'no' if copying a single file
        delete: no
        compress: yes
        rsync_opts:
          - "--rsh='ssh -o StrictHostKeyChecking=no'"
      delegate_to: "{{ inventory_hostname }}"
      vars:
        ansible_ssh_extra_args: "-o ProxyJump={{ src_host }}"
