---
- name: Connect as webadm and kill Standalone processes
  hosts: all
  remote_user: webadm
  become: yes

  tasks:
    - name: Check current user
      command: whoami
      register: whoami_output

    - name: Display current user
      debug:
        msg: "Current user is {{ whoami_output.stdout }}"

    - name: Kill all processes with 'Standalone' in their name
      shell: |
        ps -ef | grep Standalone | grep -v grep | awk '{print $2}' | xargs -r kill -9
      args:
        warn: false
      ignore_errors: yes

    - name: Show completed if all tasks are completed
      debug:
        msg: "completed"
