---
- name: Kill all 'nc -l' processes as root
  hosts: all
  remote_user: root
  become: yes

  tasks:
    - name: Kill all processes with 'nc -l' in their name
      shell: |
        ps -ef | grep 'nc -l' | grep -v grep | awk '{print $2}' | xargs -r kill -9
      args:
        warn: false
      ignore_errors: yes
