---
- name: Kill all running netcat (nc) processes
  hosts: all
  become: yes
  tasks:
    - name: Kill all netcat (nc) processes
      ansible.builtin.shell: |
        pkill -f 'nc'
      ignore_errors: yes
      register: kill_nc_result

    - name: Output result
      ansible.builtin.debug:
        var: kill_nc_result
